### PR TITLE
Fixed errors running person detector Google Colab

### PR DESCRIPTION
**Pull request by alexjones85**
I had some errors on the person_detector notebook. Specifically with the config file anchors, some training variables missing, and a spelling mistake in augmentation. 
This worked for me running in Google Colab but not sure if it creates any other issues making these changes?
One other issue is there didn't seem to be a kmodel file output, only a tflite model.
I'm not a coder, so only just learning this process. Let me know if I'm not following the right procedure here as well?

### CODE REVIEW

**Comment by AIWintermuteAI** [comment]
This should be fine. The notebook wasn't update to YOLOv3.

**Comment by alexjones85** [comment]
I'm having trouble figuring out why I can't get the kmodel file to output. I've tried the person_detector and the pascal20_detector but only the tflite model is output. So I can troubleshoot, do you know if any of the notebooks in the resources folder are outputting the kmodel file in either YOLOv3 or v2?

**Comment by AIWintermuteAI** [comment]
Can you share you notebook with outputs?

**Comment by alexjones85** [comment]
What's the easiest way to share with outputs? Like this:
https://colab.research.google.com/drive/1oEGBkgzcorqgs1el9Z2sLMWSNyhn_Hfx?usp=sharing

**Comment by AIWintermuteAI** [comment]
I think it was failing because of the path to either converter/dataset or the model. I'm guessing you had some problems downloading the dataset from GDrive, so you changed the path. 
I did a few modifications and it works now.
image
Another things is that MobileNet7_5 does not work with 240-320 YOLOv3 for K210, so you can scale it down to MobileNet5_0.

**Comment by AIWintermuteAI** [comment]
Updated the notebook in master.

**Pull request merged**
